//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamiZarf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HamiZarfDB : DbContext
    {
        public HamiZarfDB()
            : base("name=HamiZarfDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AllPage> AllPages { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ChildCategory> ChildCategories { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Motto> Mottoes { get; set; }
        public virtual DbSet<ParentCategory> ParentCategories { get; set; }
        public virtual DbSet<PictureForParentCategory> PictureForParentCategories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<SocialNetworksLink> SocialNetworksLinks { get; set; }
    
        public virtual int Sp_DeleteChildCategory(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteChildCategory", idParameter);
        }
    
        public virtual int Sp_DeleteContactUs(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteContactUs", idParameter);
        }
    
        public virtual int Sp_DeleteContent(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteContent", idParameter);
        }
    
        public virtual int Sp_DeleteParentCategory(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteParentCategory", idParameter);
        }
    
        public virtual int Sp_DeleteProduct(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteProduct", idParameter);
        }
    
        public virtual int Sp_DeleteSocialNetworkLinks(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteSocialNetworkLinks", idParameter);
        }
    
        public virtual ObjectResult<Sp_Get4Content_Result> Sp_Get4Content(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get4Content_Result>("Sp_Get4Content", iParameter);
        }
    
        public virtual ObjectResult<sp_getallchildcategoryOk_Result> sp_getallchildcategoryOk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getallchildcategoryOk_Result>("sp_getallchildcategoryOk");
        }
    
        public virtual ObjectResult<sp_getallparentcategoryOk_Result> sp_getallparentcategoryOk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getallparentcategoryOk_Result>("sp_getallparentcategoryOk");
        }
    
        public virtual int Sp_InsertChildCategory(string name, Nullable<int> p_category_id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var p_category_idParameter = p_category_id.HasValue ?
                new ObjectParameter("p_category_id", p_category_id) :
                new ObjectParameter("p_category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertChildCategory", nameParameter, p_category_idParameter);
        }
    
        public virtual int Sp_InsertContactUs(string name, string email, string txt, string subject)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertContactUs", nameParameter, emailParameter, txtParameter, subjectParameter);
        }
    
        public virtual int Sp_InsertParentCategory(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertParentCategory", nameParameter);
        }
    
        public virtual int Sp_InsertProduct(string name, Nullable<decimal> price, string txt, Nullable<int> p_Cat_Id, Nullable<int> c_Cat_Id, string unit, Nullable<bool> isavailable, byte[] pic)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var p_Cat_IdParameter = p_Cat_Id.HasValue ?
                new ObjectParameter("p_Cat_Id", p_Cat_Id) :
                new ObjectParameter("p_Cat_Id", typeof(int));
    
            var c_Cat_IdParameter = c_Cat_Id.HasValue ?
                new ObjectParameter("C_Cat_Id", c_Cat_Id) :
                new ObjectParameter("C_Cat_Id", typeof(int));
    
            var unitParameter = unit != null ?
                new ObjectParameter("unit", unit) :
                new ObjectParameter("unit", typeof(string));
    
            var isavailableParameter = isavailable.HasValue ?
                new ObjectParameter("isavailable", isavailable) :
                new ObjectParameter("isavailable", typeof(bool));
    
            var picParameter = pic != null ?
                new ObjectParameter("pic", pic) :
                new ObjectParameter("pic", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertProduct", nameParameter, priceParameter, txtParameter, p_Cat_IdParameter, c_Cat_IdParameter, unitParameter, isavailableParameter, picParameter);
        }
    
        public virtual ObjectResult<Sp_SelectAllProdductOK_Result> Sp_SelectAllProdductOK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SelectAllProdductOK_Result>("Sp_SelectAllProdductOK");
        }
    
        public virtual ObjectResult<Sp_SelectProductById_Result> Sp_SelectProductById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_SelectProductById_Result>("Sp_SelectProductById", idParameter);
        }
    
        public virtual ObjectResult<sp_ShowAllContents_Result> sp_ShowAllContents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ShowAllContents_Result>("sp_ShowAllContents");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_sp_getidchildcategory(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_sp_getidchildcategory", iParameter);
        }
    
        public virtual ObjectResult<sp_sp_getproductbychildvategory_Result> sp_sp_getproductbychildvategory(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_getproductbychildvategory_Result>("sp_sp_getproductbychildvategory", iParameter);
        }
    
        public virtual ObjectResult<sp_sp_showchildcategorybyparentid_Result> sp_sp_showchildcategorybyparentid(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_showchildcategorybyparentid_Result>("sp_sp_showchildcategorybyparentid", iParameter);
        }
    
        public virtual ObjectResult<sp_sp_showcontent_Result> sp_sp_showcontent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_showcontent_Result>("sp_sp_showcontent");
        }
    
        public virtual ObjectResult<sp_sp_showparentcategory_Result> sp_sp_showparentcategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_showparentcategory_Result>("sp_sp_showparentcategory");
        }
    
        public virtual ObjectResult<sp_sp_showProdcuts_Result> sp_sp_showProdcuts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_showProdcuts_Result>("sp_sp_showProdcuts");
        }
    
        public virtual ObjectResult<sp_sp_showslider_Result> sp_sp_showslider()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_showslider_Result>("sp_sp_showslider");
        }
    
        public virtual ObjectResult<sp_sp_sp_getchildcategorybyid_Result> sp_sp_sp_getchildcategorybyid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_sp_getchildcategorybyid_Result>("sp_sp_sp_getchildcategorybyid");
        }
    
        public virtual ObjectResult<sp_sp_sp_getproductBychildcategoryb_id_Result> sp_sp_sp_getproductBychildcategoryb_id(Nullable<int> ii)
        {
            var iiParameter = ii.HasValue ?
                new ObjectParameter("ii", ii) :
                new ObjectParameter("ii", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_sp_getproductBychildcategoryb_id_Result>("sp_sp_sp_getproductBychildcategoryb_id", iiParameter);
        }
    
        public virtual ObjectResult<sp_sp_sp_GetProductBySelectCategoryNUMBER_Result> sp_sp_sp_GetProductBySelectCategoryNUMBER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sp_sp_GetProductBySelectCategoryNUMBER_Result>("sp_sp_sp_GetProductBySelectCategoryNUMBER");
        }
    
        public virtual int sp_sp_sp_spgetpicforthisparentcategory(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sp_sp_spgetpicforthisparentcategory", iParameter);
        }
    
        public virtual int sp_spEditeMotto(string motto)
        {
            var mottoParameter = motto != null ?
                new ObjectParameter("motto", motto) :
                new ObjectParameter("motto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_spEditeMotto", mottoParameter);
        }
    
        public virtual ObjectResult<sp_spshowMotto_Result> sp_spshowMotto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_spshowMotto_Result>("sp_spshowMotto");
        }
    
        public virtual int Sp_UpdateParentCategory(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateParentCategory", idParameter, nameParameter);
        }
    
        public virtual int Sp_UpdateProduct(Nullable<int> id, string name, string unit, Nullable<int> p_Cat_Id, Nullable<int> c_Cat_Id, string txt, Nullable<decimal> price, Nullable<bool> isavailable)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var unitParameter = unit != null ?
                new ObjectParameter("unit", unit) :
                new ObjectParameter("unit", typeof(string));
    
            var p_Cat_IdParameter = p_Cat_Id.HasValue ?
                new ObjectParameter("P_Cat_Id", p_Cat_Id) :
                new ObjectParameter("P_Cat_Id", typeof(int));
    
            var c_Cat_IdParameter = c_Cat_Id.HasValue ?
                new ObjectParameter("C_Cat_Id", c_Cat_Id) :
                new ObjectParameter("C_Cat_Id", typeof(int));
    
            var txtParameter = txt != null ?
                new ObjectParameter("txt", txt) :
                new ObjectParameter("txt", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            var isavailableParameter = isavailable.HasValue ?
                new ObjectParameter("isavailable", isavailable) :
                new ObjectParameter("isavailable", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateProduct", idParameter, nameParameter, unitParameter, p_Cat_IdParameter, c_Cat_IdParameter, txtParameter, priceParameter, isavailableParameter);
        }
    
        public virtual ObjectResult<Sp_sp_sp_GetAllrproductBySelectOfset_Result> Sp_sp_sp_GetAllrproductBySelectOfset(Nullable<int> pagenumber, Nullable<int> pagesize)
        {
            var pagenumberParameter = pagenumber.HasValue ?
                new ObjectParameter("pagenumber", pagenumber) :
                new ObjectParameter("pagenumber", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_sp_sp_GetAllrproductBySelectOfset_Result>("Sp_sp_sp_GetAllrproductBySelectOfset", pagenumberParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<Sp_sp_sp_GetAllrproductBySelectOfsetfullsale_Result> Sp_sp_sp_GetAllrproductBySelectOfsetfullsale(Nullable<int> pagenumber, Nullable<int> pagesize)
        {
            var pagenumberParameter = pagenumber.HasValue ?
                new ObjectParameter("pagenumber", pagenumber) :
                new ObjectParameter("pagenumber", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_sp_sp_GetAllrproductBySelectOfsetfullsale_Result>("Sp_sp_sp_GetAllrproductBySelectOfsetfullsale", pagenumberParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<Sp_sp_sp_GetAllrproductBySelectOfsetnew_Result> Sp_sp_sp_GetAllrproductBySelectOfsetnew(Nullable<int> pagenumber, Nullable<int> pagesize)
        {
            var pagenumberParameter = pagenumber.HasValue ?
                new ObjectParameter("pagenumber", pagenumber) :
                new ObjectParameter("pagenumber", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_sp_sp_GetAllrproductBySelectOfsetnew_Result>("Sp_sp_sp_GetAllrproductBySelectOfsetnew", pagenumberParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<Sp_sp_sp_GetAllrproductBySelectOfsetSpecial_Result> Sp_sp_sp_GetAllrproductBySelectOfsetSpecial(Nullable<int> pagenumber, Nullable<int> pagesize)
        {
            var pagenumberParameter = pagenumber.HasValue ?
                new ObjectParameter("pagenumber", pagenumber) :
                new ObjectParameter("pagenumber", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_sp_sp_GetAllrproductBySelectOfsetSpecial_Result>("Sp_sp_sp_GetAllrproductBySelectOfsetSpecial", pagenumberParameter, pagesizeParameter);
        }
    }
}
