//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamiZarf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureForParentCategory
    {
        public int Id { get; set; }
        public byte[] img { get; set; }
        public Nullable<int> P_Cat_Id { get; set; }
    
        public virtual ParentCategory ParentCategory { get; set; }
    }
}
